[project]
name = "llm-food-safety-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "httpx>=0.28.1",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "typing>=3.10.0.0",
]
